# Generated by Django 4.2.1 on 2023-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
