# Generated by Django 4.2.1 on 2023-05-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
