# Generated by Django 4.2.1 on 2023-05-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_rename_products_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
