# Generated by Django 4.2.1 on 2023-06-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_rename_price_product_prise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prise',
            new_name='price',
        ),
    ]
